### ISSUE TITLE
Improve Profile Viewer Performance/Loading Display

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#74] opened 2021-07-01 19:05 UTC
As a user of the OSCAL viewer app or underlying React components, I want Profiles to be resolved and displayed in a timely manner so that my workflow is not disturbed by waiting for the page to load.

### Acceptance Criteria
* The Profile viewer loads the [FedRAMP moderate profile](https://raw.githubusercontent.com/GSA/fedramp-automation/master/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline_profile.json) in 2 seconds or less in the live sandbox environment
* If the complete rendering takes longer than 0.5 seconds a loading indicator should be displayed for any area taking time to render

### Implementation Notes
* The [Material-UI Skeleton component ](https://material-ui.com/components/skeleton/) should be considered
* Note that we’ll address any loading indicator additions to other viewers in a future issue

**Comment by rgauss** [comment] 2021-07-28 20:48
@Bronstrom, is there any update on this?

**Comment by Bronstrom** [comment] 2021-07-28 21:18
@rgauss, @zclarkEDC and I had been discussing the skeleton component not display problem earlier this week. The skeleton component displays locally when running `npm run start` (runs microbundle-crl with the watch command), while `npm run build` (runs microbundle-crl excluding the watch command) doesn't display it. The size of `index.modern.js*` files in the `./dist` directory change after running these commands in the root project directory. An idea we exhausted is the css modules aren't being imported properly when running `build`. This seems like a strange issue because they are practically the same commands, just one runs watch. At this point, we're thinking the problem is outside the scope of #74. Was curious if anyone else has ideas on this.

**Comment by rgauss** [comment] 2021-07-28 21:22
@Bronstrom, the skeleton also does not seem to render in the sandbox environment (though that could be due to pipeline issues which have hopefully just recently been resolved).

Can you look at building a distribution of the example app and see if it renders there?  That's really the target.

**Comment by Bronstrom** [comment] 2021-07-29 15:21
I'm pretty sure the pipeline for the live environment is running `npm run build`, which like when run locally doesn't render the skeleton component. Same problem when building a distribution of example app.

**Comment by tuckerzp** [comment] 2021-08-13 16:56
Would #152 close this? Or are they two separate issues?

**Comment by rgauss** [comment] 2021-08-13 17:30
@tuckerzp, yes, #152 would close this provided it works in a distribution build and the sandbox environment.

**Closed** 2021-12-02 14:15 UTC
Labels: enhancement
