### ISSUE TITLE
React error unless creating a ref for every editable field

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#499] opened 2022-07-13 20:03 UTC
With our current approach of creating refs in the `setParametersRef`s array, a ref is being created for every editable field, for every control statement/prose, and for every component before the user has even asked to edit. However, other attempts resulted in a React error of: "Rendered more hooks than during the previous render." This should be investigated further so that we can see if there is a way to only create refs once the user has asked to edit.

https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/OSCALControlProse.js#L366-L370

**Comment by kylelaker** [comment] 2022-08-05 00:33
Duplicate of #390

**Closed by kylelaker** 2022-08-05 00:33 UTC
