### ISSUE TITLE
Viewer Crashes on Load of Wrong OSCAL Doc Type

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#240] opened 2022-02-08 12:02 UTC
Currently the viewer app crashes when loading a URL with the wrong OSCAL object type, i.e. reloading an SSP URL in the Catalog Viewer

### Steps to Reproduce
1. Navigate to the [sandbox viewer environment](https://oscal-viewer.msd.easydynamics.com/)
2. Paste an SSP URL into the URL input and click Reload

### Expected Behavior
3. An error is shown (standard red bar with 'Yikes') that indicates the URL response could not be parsed

### Actual Behavior
3. The page crashes (white page with no error is shown)

### Implementation Notes
- We want to be sure this is fixed for all 'root' OSCAL objects, not just catalogs.
- We'll want an automated end-to-end (Cypress) test to confirm behavior

**Comment by zclarkEDC** [comment] 2022-02-09 19:23
Taking a look at this today @rgauss

**Comment by kylelaker** [comment] 2022-02-11 02:01
@zclarkEDC I was playing around with this and created https://github.com/EasyDynamics/oscal-react-library/compare/feature/doc-type-crash which may be useful. It doesn't fully take care of the the second implementation note (adding the test) and I think we can go further and cleanup more of the `onError`/`setError` stuff. I also didn't really document anything. We also may not want that `console.error`.

Information on Error Boundaries can be found at: https://reactjs.org/docs/error-boundaries.html. The way error handling changed in React 16+ to just unmount the whole app is at https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html.

![image](https://user-images.githubusercontent.com/850893/153526777-2b17c09c-46bb-476b-a42d-29dec73aade5.png)

A sample is in the screenshot. Note that while "Reload" doesn't look disabled (as expected until #163 is fixed), if you click it, it doesn't do anything and it then becomes gray.

**Comment by zclarkEDC** [comment] 2022-02-18 19:26
> @zclarkEDC I was playing around with this and created https://github.com/EasyDynamics/oscal-react-library/compare/feature/doc-type-crash which may be useful. It doesn't fully take care of the the second implementation note (adding the test) and I think we can go further and cleanup more of the `onError`/`setError` stuff. I also didn't really document anything. We also may not want that `console.error`.
> 
> Information on Error Boundaries can be found at: https://reactjs.org/docs/error-boundaries.html. The way error handling changed in React 16+ to just unmount the whole app is at https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html.
> 
> ![image](https://user-images.githubusercontent.com/850893/153526777-2b17c09c-46bb-476b-a42d-29dec73aade5.png)
> 
> A sample is in the screenshot. Note that while "Reload" doesn't look disabled (as expected until #163 is fixed), if you click it, it doesn't do anything and it then becomes gray.

When reloading with 
```https://raw.githubusercontent.com/usnistgov/oscal-content/master/examples/ssp/json/ssp-example.json```
on ```http://localhost:3000/catalog```.....
I get the result of your screenshot, and then it crashes with the familiar:
![same error](https://user-images.githubusercontent.com/70411989/154748802-28a67ae5-bcaf-49ca-95e3-5ed6178895bf.PNG)

**Comment by kylelaker** [comment] 2022-02-18 20:32
> When reloading with `https://raw.githubusercontent.com/usnistgov/oscal-content/master/examples/ssp/json/ssp-example.json` on `http://localhost:3000/catalog`..... I get the result of your screenshot, and then it crashes with the familiar: ![same error](https://user-images.githubusercontent.com/70411989/154748802-28a67ae5-bcaf-49ca-95e3-5ed6178895bf.PNG)
> 
> This behavior is occurring on the doc-type-crash branch.

That is because you're running locally with a development server. If you ran on the develop branch, you'd see the same. But that's not the "crash" -- that's the dev server presenting error details. In production, I believe it would stay on the app page (which you'll see if you press the X there). Much like if you ran the `develop` branch and clicked that "X" you'd see the white page with the app unmounted,

**Comment by kylelaker** [comment] 2022-02-22 16:18
I have confirmed that doing `npm run build && cd build && serve .` _does not_ display that full-page error dialog (as I expected). Doing that mimics a "production" build, which is what happens in the live sandbox environment as well. So a production build displays the "Yikes!" error and _stays mounted_.

**Comment by kylelaker** [comment] 2022-02-22 22:04
The fix itself has been merged but we are still going to need to wait until the test(s) have been written.

**Comment by rgauss** [comment] 2022-03-11 00:44
Cypress tests in PR: EasyDynamics/oscal-editor-deployment#53

**Closed** 2022-03-22 12:37 UTC
Labels: bug
