### ISSUE TITLE
Display System Inventory Items

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#401] opened 2022-05-20 18:56 UTC
An SSP may require a "system inventory" section that maps to `system-implementation/inventory-items` ([see schema docs here](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/system-implementation/inventory-items)). As a user that wants to view and edit such an SSP in the OSCAL Viewer, I want a visual representation of the inventory items.

### Implementation Notes
The `inventory-items` array can be quite large, so some type of scroll or dropdown UI element should be used so that not all of them take up too much real estate at one time.

### Acceptance Criteria
- A UI element to display `system-implementation/inventory items` is available in the OSCAL Viewer
- Tests are added for the new UI element

**Comment by rgauss** [comment] 2022-05-20 20:12
Closing as a duplicate of #224 (to which I've added your implementation notes).

**Closed by rgauss** 2022-05-20 20:12 UTC
Labels: enhancement
